version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'requestsPostgres'
    environment:
      - 'POSTGRES_DB=requests'
      - 'POSTGRES_USERNAME=postgres'
      - 'POSTGRES_PASSWORD=0000'
    ports:
      - "5432:5432"

    networks:
      - backend

  app:
    build: /.
    container_name: 'request-java-app'
    ports:
      - "8080:8080"
    environment:
     - 'DB_URL=jdbc:postgresql://postgres:5432/requests'
     - 'DB_USERNAME=postgres'
     - 'DB_PASSWORD=0000'

    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:

volumes:
  pg-data:

